name: Build rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout MetaCubeX/meta-rules-converter
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/meta-rules-converter
          path: convert

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: ./convert/go.sum

      - name: Get geoip.dat and geosite.dat files
        run: |
          wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat

      - name: Build db and metadb file
        env:
          NO_SKIP: true
        run: |
          go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
          geo convert site -i v2ray -o sing -f geosite.db ./geosite.dat
          geo convert ip   -i v2ray -o sing -f geoip.db ./geoip.dat
          geo convert ip   -i v2ray -o meta -f geoip.metadb ./geoip.dat

      - name: Convert geo to sing-rule-set
        env:
          NO_SKIP: true
        run: |
          mkdir -p sing-rule/geo/geosite && mkdir -p sing-rule/geo/geoip
          cd convert
          go run ./ geosite -f ../geosite.dat -o ../sing-rule/geo/geosite -t sing-box
          go run ./ geoip -f ../geoip.dat -o ../sing-rule/geo/geoip -t sing-box

      - name: Convert geo to meta-rule-set
        env:
          NO_SKIP: true
        run: |
          mkdir -p meta-rule/geo/geosite && mkdir -p meta-rule/geo/geoip
          cd convert
          go run ./ geosite -f ../geosite.dat -o ../meta-rule/geo/geosite
          go run ./ geoip -f ../geoip.dat -o ../meta-rule/geo/geoip

      - name: Convert asn
        env:
          NO_SKIP: true
        run: |
          mkdir -p meta-rule/asn && mkdir -p sing-rule/asn
          wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb
          cd convert
          go run ./ asn -f ../GeoLite2-ASN.mmdb -o ../meta-rule/asn
          go run ./ asn -f ../GeoLite2-ASN.mmdb -o ../sing-rule/asn -t sing-box

      - name: Move and zip files
        run: |
          mkdir -p ./publish/
          wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O ./publish/country.mmdb
          install -Dp ./geoip.dat ./publish/
          install -Dp ./geosite.dat ./publish/
          install -Dp ./geosite.db ./publish/
          install -Dp ./geoip.db ./publish/
          install -Dp ./geoip.metadb ./publish/
          install -Dp ./GeoLite2-ASN.mmdb ./publish/
          cd ./publish || exit 1
          sha256sum country.mmdb       > country.mmdb.sha256sum
          sha256sum geoip.dat          > geoip.dat.sha256sum
          sha256sum geosite.dat        > geosite.dat.sha256sum
          sha256sum geosite.db         > geosite.db.sha256sum
          sha256sum geoip.db           > geoip.db.sha256sum
          sha256sum geoip.metadb       > geoip.metadb.sha256sum
          sha256sum GeoLite2-ASN.mmdb  > GeoLite2-ASN.mmdb.sha256sum

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ env.BUILDTIME }}
          tag: latest
          file_glob: true
          overwrite: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Git push assets to "sing-rule" branch
        run: |
          cd sing-rule || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b sing
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin sing

      - name: Git push assets to "meta-rule" branch
        run: |
          cd meta-rule || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b meta
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin meta

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
